### ISSUE TITLE
Terabox download fails with error 9019

### ISSUE THREAD

**Issue by jonatino** [bipinkrish/Link-Bypasser-Bot#106]
link: https://www.terabox.com/sharing/link?surl=usKkgXkqf63yIOLx9Gh2Dg

response:
```{"errno":9019,"errmsg":"need verify","request_id":540355135493956590}```

**Comment by bipinkrish** [comment]
it should be of the form https://teraboxapp.com/s/1l2o7nRmpxJZZuq4Zsw4zeA
