### ISSUE TITLE
Add feature join telegram channel to use the bot

### ISSUE THREAD

**Issue by ScripterSaurav** [bipinkrish/Link-Bypasser-Bot#11]
Add feature join  telegram channel to use the bot.

**Comment by rubandurai27** [comment]
How to deploy ?

**Comment by ScripterSaurav** [comment]
> How to deploy ?

On heroku or vercel

**Comment by rubandurai27** [comment]
Demo video available ?

**Comment by bipinkrish** [comment]
This is for personal use, i will not add restrictions
