### ISSUE TITLE
Tnshort links are not getting bypassed

### ISSUE THREAD

**Issue by Priyanshuadeveloper** [bipinkrish/Link-Bypasser-Bot#135]
This is the link which I have paste in the bot - **https://link.tnshort.net/2l9EX**

And, I am getting this message in reply - **Not in Supported Sites**

Please fix this issue soon.

**Comment by Jegaa1** [comment]
> https://link.tnshort.net/2l9EX

https://drive.google.com/file/d/1Swqf6IA7xxe_wY12b6r1HuU8qrdJNP2V/view?usp=drivesdk

**Comment by Jegaa1** [comment]
> This is the link which I have paste in the bot - **https://link.tnshort.net/2l9EX**
> 
> And, I am getting this message in reply - **Not in Supported Sites**
> 
> Please fix this issue soon.

Msg me in ur doubt @JAsuran2p0

**Comment by Priyanshuadeveloper** [comment]
Yes, Thank You it is working now.
