### ISSUE TITLE
Add kolop bypass

### ISSUE THREAD

**Issue by AnshumanPM** [bipinkrish/Link-Bypasser-Bot#14]
Hello sir,
I am using 2 different bot for mdisk and kolop.
Please help us to add kolop bypass features in this repo.

Waiting for reply/commit

**Comment by AnshumanPM** [comment]
[This ](https://github.com/majnurangeela/BypassBot) may help you

**Comment by AnshumanPM** [comment]
Request to add all gd bypass present in that repo

**Comment by bipinkrish** [comment]
sure, I'll add anything that is possible

**Comment by bipinkrish** [comment]
done
