### ISSUE TITLE
Not Perfectly Working On Group

### ISSUE THREAD

**Issue by AnshumanPM** [bipinkrish/Link-Bypasser-Bot#15]
https://user-images.githubusercontent.com/95046825/192409737-a03a0be9-38ec-46bf-af64-b00a59c9518d.mp4

It's perfectly working in PM but when I use in group and sending command with mentioning the bot it says it's invalid.
Please try fix

**Comment by bipinkrish** [comment]
see the command that has bot username, it's gets the output, in group it is mandatory to use username, it's not bot's limitation.
