### ISSUE TITLE
Sending Useless Command In Group

### ISSUE THREAD

**Issue by AnshumanPM** [bipinkrish/Link-Bypasser-Bot#32]
https://user-images.githubusercontent.com/95046825/199378324-59a9a7c4-67ad-4836-943a-fedbfa9ed5cc.mp4

It's Not Compatible with group, It responding on any command. Please fix this problem for group.

**Comment by kctelegram3** [comment]
Remove # see help Section from Main.py

**Comment by AnshumanPM** [comment]
> Remove # see help Section from Main.py

Thanks
Working 👍
