### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Richnix** [bipinkrish/Link-Bypasser-Bot#35]
![Screenshot_2022-11-06-21-38-08-006_ir ilmili telegraph second](https://user-images.githubusercontent.com/114581724/200181530-41e1bc7b-86c3-4472-97ac-3d8bfd294a3a.jpg)

**Comment by bipinkrish** [comment]
this link is supported by Pybypass, you need to open an issue there

**Comment by bipinkrish** [comment]
this issue is fixed
