### ISSUE TITLE
Not Working any links

### ISSUE THREAD

**Issue by AnshumanPM** [bipinkrish/Link-Bypasser-Bot#37]
![Screenshot_2022_1107_151000](https://user-images.githubusercontent.com/95046825/200278207-e1850997-724c-4900-ac19-7f00bc9ca424.jpg)

**Comment by bipinkrish** [comment]
I will check this soon

**Comment by AnshumanPM** [comment]
> I will check this soon

Ho sake to command wapas add kardo.
Group ke liye achha nahi hai. Mera leching group me disturb kar raha hai.

**Comment by AnshumanPM** [comment]
Make a bool COMMANDS = True/False
It'll be better.

**Comment by bipinkrish** [comment]
> Make a bool COMMANDS = True/False It'll be better.

Explain more

**Comment by bipinkrish** [comment]
> ![Screenshot_2022_1107_151000](https://user-images.githubusercontent.com/95046825/200278207-e1850997-724c-4900-ac19-7f00bc9ca424.jpg)

this issue if fixed

**Comment by AnshumanPM** [comment]
> > Make a bool COMMANDS = True/False It'll be better.
> 
> Explain more

Make a config.py file & add all config there [Like this](https://github.com/arshsisodiya/helios-mirror/blob/master/config_sample.env) .
& If we set BOT_PM = True in This config then files are sent to PM & if False files are sent to dump channel.

Like this creates a variable name 'COMMANDS'
If we set COMMANDS = True then it will listen to link with command, If we type COMMANDS = False or didn't fill then it will listen to link (no need of command)
