### ISSUE TITLE
Infinity polling exception: list index out of range

### ISSUE THREAD

**Issue by Tarunteja003** [bipinkrish/Link-Bypasser-Bot#4]
![Screenshot_20220812_195126](https://user-images.githubusercontent.com/105418078/184373732-cdb16708-a176-4896-b73c-1383a6037729.jpg)

**Comment by bipinkrish** [comment]
Usage :
```
 /rl link
```

**Comment by aakash2021-cap** [comment]
> ![Screenshot_20220812_195126](https://user-images.githubusercontent.com/105418078/184373732-cdb16708-a176-4896-b73c-1383a6037729.jpg)

Bro don't use termux or any server coz this error happen

Use vps or any Ubuntu server it's work well

**Comment by Tarunteja003** [comment]
> 

Thanks bro

**Comment by Tarunteja003** [comment]
> 



> > ![Screenshot_20220812_195126](https://user-images.githubusercontent.com/105418078/184373732-cdb16708-a176-4896-b73c-1383a6037729.jpg)
> 
> Bro don't use termux or any server coz this error happen
> 
> Use vps or any Ubuntu server it's work well

It is vps ... I just used it wrong

Thanks anyway

**Comment by Tarunteja003** [comment]
> Usage :
> 
> ```
>  /rl link
> ```

Failed to Bypass: 'NoneType' object has no attribute 'find_all'

Error with rocklink

**Comment by bipinkrish** [comment]
> > Usage :
> > ```
> >  /rl link
> > ```
> 
> Failed to Bypass: 'NoneType' object has no attribute 'find_all'
> 
> Error with rocklink

Not every link can be bypassed, and I am not the owner of the bypassing code. I just made bot interface. You can visit github profile of original owners from credits and ask them
