### ISSUE TITLE
GDTOT Crypt Missing Issue

### ISSUE THREAD

**Issue by JOHN748** [bipinkrish/Link-Bypasser-Bot#44]
Bro I've filled my gdtot crypt in bypasser.py file but when I'm trying to bypass the gdtot links it just shows this error in my bot.

Error: Missing required parameter 'gdtot_crypt'. Please enter your GDOT crypt value.

![image](https://user-images.githubusercontent.com/48284893/204404319-6222a917-a450-44e0-ab00-7b77bcc88797.png)

Can you please help me on this!

**Comment by bipinkrish** [comment]
> Bro I've filled my gdtot crypt in bypasser.py file but when I'm trying to bypass the gdtot links it just shows this error in my bot.
> 
> Error: Missing required parameter 'gdtot_crypt'. Please enter your GDOT crypt value.
> 
> ![image](https://user-images.githubusercontent.com/48284893/204404319-6222a917-a450-44e0-ab00-7b77bcc88797.png)
> 
> Can you please help me on this!

fixed
