### ISSUE TITLE
Bypass Using Command

### ISSUE THREAD

**Issue by NesamaniX1** [bipinkrish/Link-Bypasser-Bot#45]
![IMG_20221208_110933_597](https://user-images.githubusercontent.com/77948100/206366533-3d90733d-a5a8-434a-a2af-77789f3c03bc.jpg)
![IMG_20221208_110937_148](https://user-images.githubusercontent.com/77948100/206366558-921d1c50-762a-44fd-8b4d-2cba34fffde8.jpg)
Bypass The All Short Links Using common Command
Example : 
 `/bypass https://link.tnlink.in/EJB4biz`
output : https://t.me/incmassfilesbot?`start=Z2V0LTM4ODk3MDQzNzc0ODIxNjI4`
`/bypass https://urlsopen.com/f3Wn `
Output : https://premium.nanthakps.ml/0:/www.1TamilMV.men%20-%20Naanum%20Rowdy%20Dhaan%20(2015)%20Tamil%20TRUE%20WEB-DL%20-%201080p%20HQ%20-%20AVC%20-%20(DD%205.1%20-%20192Kbps%20&%20AAC)%20-%203.9GB%20-%20ESub.mkv

**Comment by bipinkrish** [comment]
you don't need commands, you can just send any supported links and get the result
