### ISSUE TITLE
Terabox

### ISSUE THREAD

**Issue by Jegaa1** [bipinkrish/Link-Bypasser-Bot#83]
Not working Terabox

And plz add some feature

Same Inputs come with bypassing output
![Screenshot_2023-06-29-16-27-51-660_ir ilmili telegraph second](https://github.com/bipinkrish/Link-Bypasser-Bot/assets/121353390/92cbd84f-917b-495d-bce7-f0cac36ec8d2)

**Comment by bipinkrish** [comment]
Fixed
