### ISSUE TITLE
Needed help with config

### ISSUE THREAD

**Issue by FilmBee** [bipinkrish/Link-Bypasser-Bot#86]
Brother i am genuinely confused about what are all the variables names for appdrive and gdflix.. When i send any gdflix link to the bot i get thos type of message:
ERROR: Key not found!

And i get this for appdrive:
ERROR: This link don't have direct download button

How can i add my variables for these if i wanna use it to bypass using my account?

**Comment by bipinkrish** [comment]
You can set ENV Variables
