### ISSUE TITLE
Bypass Error

### ISSUE THREAD

**Issue by devilxsam** [bipinkrish/Link-Bypasser-Bot#98]
I put this repo in my VPS server, it is running and the start message is also coming, but as soon as I enter the link, no response comes.

**Comment by bipinkrish** [comment]
Show me logs

**Comment by devilxsam** [comment]
Showing this in logs 

Connected
Retrying
Retrying
Retrying
Retrying

**Comment by bipinkrish** [comment]
That's all the logs?

**Comment by devilxsam** [comment]
When I send the link of Tera box, no response comes. And the remaining links response comes. 

But your bot working perfectly with tera box how..?

**Comment by bipinkrish** [comment]
You should add terabox cookie

**Comment by bipinkrish** [comment]
You should add terabox cookie

**Comment by devilxsam** [comment]
I added all cookies

Check here : https://github.com/devilxsam/Link-Bypasser-Bot/

**Comment by devilxsam** [comment]
After adding cookies.. same error showing

**Comment by bipinkrish** [comment]
Then how is my bot is working? clear the cache and redeploy
